### ISSUE TITLE
Publish to Open VSX?

### ISSUE THREAD

**Issue by jmezzacappa** [bertolinimarco/vscode-theme-newton-next#1]
Are there any plans to publish it to [Open VSX](https://open-vsx.org/)? It would be nice to be able to easily install it in other editors, like VSCodium, Onivim 2, etc.

Also, thanks for this great theme :) It's one of my favorites.

**Comment by bertolinimarco** [comment]
Hey @jmezzacappa thanks for asking, I've just published it :) 

https://open-vsx.org/extension/devberto/theme-newton-next

Thank you for using Newton Next!
